let fonts = {
    'Open-Dyslexic' : '/fonts/OpenDyslexic-Regular.otf',
    'Arial' : '',
    'Comic Sans' : '',
    'Verdana' : '',
    'Tahoma' : '',
    'Trebuchet ' : '',
    'Calibri' : '',
    'Open Sans' : '',
    'Helvetica' : '',
    'Lexia Readable' : '/fonts/LexieReadable-Regular.ttf',
    'Nisaba' : '/fonts/Nisaba.ttf',
    'Reading Regular' : '/fonts/Reading Regular.otf',
    'Sylexiad-Serif' : '/fonts/SylexiadSerifThin-BoldItalic.otf',
    'Sylexiad-Sans' : '/fonts/SylexiadSansThin-BoldItalic.otf',
};
